In [1]:
import torch
import torch.nn.functional as F
import math

def scaled_dot_product_attention(Q: torch.Tensor, K: torch.Tensor, V: torch.Tensor) -> torch.Tensor:
    """
    Compute scaled dot-product attention.
    """
    # Yo lesss do it
    d_k=Q.size(-1)  #dimensions of key vectors

    #now QK^transpose
    scores=torch.matmul(Q,K.transpose(-2,-1))
    scores=scores/math.sqrt(d_k)

    #now softmax -> attention weights

    attn_weights=F.softmax(scores,dim=-1)
    output=torch.matmul(attn_weights,V)
    return output

In [2]:
torch.set_printoptions(precision=3, sci_mode=False)

Q = torch.tensor([[[1., 0., 1.],
                   [0., 1., 1.]]])

K = torch.tensor([[[1., 1., 0.],
                   [0., 1., 1.],
                   [1., 0., 1.]]])

V = torch.tensor([[[1., 0.],
                   [0., 2.],
                   [3., 1.]]])

d_k = Q.size(-1)

scores = torch.matmul(Q, K.transpose(-2, -1))
scaled = scores / math.sqrt(d_k)
weights = F.softmax(scaled, dim=-1)
out = torch.matmul(weights, V)

print("Q =\n", Q)
print("\nK =\n", K)
print("\nV =\n", V)

print("\nQK^T =\n", scores)
print("\nScaled scores =\n", scaled)
print("\nAttention weights =\n", weights)
print("\nOutput =\n", out)

Q =
 tensor([[[1., 0., 1.],
         [0., 1., 1.]]])

K =
 tensor([[[1., 1., 0.],
         [0., 1., 1.],
         [1., 0., 1.]]])

V =
 tensor([[[1., 0.],
         [0., 2.],
         [3., 1.]]])

QK^T =
 tensor([[[1., 1., 2.],
         [1., 2., 1.]]])

Scaled scores =
 tensor([[[0.577, 0.577, 1.155],
         [0.577, 1.155, 0.577]]])

Attention weights =
 tensor([[[0.264, 0.264, 0.471],
         [0.264, 0.471, 0.264]]])

Output =
 tensor([[[1.678, 1.000],
         [1.058, 1.207]]])


In [3]:
print("\nFunction output =\n", scaled_dot_product_attention(Q, K, V))


Function output =
 tensor([[[1.678, 1.000],
         [1.058, 1.207]]])
